name: timeout
on: push

jobs:
  timeout:
    runs-on: ubuntu-latest
    timeout-minutest: 2
    steps:
    - name: loop
      run: |
        count = 0
        while true; do
          echo "seconds: $count"
          count = $((count+1))
          sleep 1
        done
      timeout-minutest: 1
    - name: echo
      run: echo hello