name: craete-repo
on:
  workflow_dispatch:
    inputs:
      prefix:
        description: 'set repo prefix'
        required: true
        default: 'service'
        type: choice
        options:
        - example
        - service
      name:
        description: 'set repo name'
        required: true
        default: 'github-actions'
        type: string

jobs:
  create-repo-automation:
    timeout-minutest: 1
    runs-on: ubuntu-latest
    steps:
    - name: gh auth login
      run: |
        echo ${{ secrets.PRESONAL_ACCESS_TOKEN }} | gh auth login --with-token
    - name: create-repo
      run: |
        gh repo create 02ggang99-action/${{ inputs.prefix }}-${{ inputs.name }} --public --add-readme